### ISSUE TITLE
todo:

### ISSUE THREAD

**Issue by ghost** [baldengineers/easytf2_mapper#14]
- [x] open/save functions 
- [x] z levels
- [x] sledge compatibility
- [x] change all file dialogs to "/" rather than "C:/"
- [x] fix corners being rotated improperly

**Comment by ghost** [comment]
ill need to look into sledge further

**Comment by ghost** [comment]
Z LEVELS ARE DONE BUT ARE SERIOUSLY BROKEN RIGHT NOW.

**Comment by ghost** [comment]
fixed z levels

**Comment by ghost** [comment]
sledge is for goldsrc rofl
