### ISSUE TITLE
issues = todo

### ISSUE THREAD

**Issue by ghost** [baldengineers/easytf2_mapper#2]
- [x] #TODO: THE CREATEPREFAB NEEDS TO ADD THE ENTITIES PART OF A CUSTOM PREFAB
                  -currently the createPrefab will not work at all with entities as they are placed after the   solids, and not in a format that would work with the current setup. big problem for now, we
- [x] #TODO: TEXTURES JESUS CHRIST ITS AN EYESORE IN HAMMER
                  -enough said
- [x] #TODO: skybox solids. will fix the lighting in game and add a final playable aspect
                  -for playtesting we need this
- [x] #TODO: add a light angle for the environment light
                  -self explanatory
- [x] #TODO: add an "entity_num" param and as a 3rd return value to EVERY SINGLE prefab.py 
  comment from toads: pass it as world_id_num and it works fine.
  comment from jony: we don't need this todo if we have try: except:
- [x] #TODO: Make createPrefab work with "parentname"

**Comment by ghost** [comment]
added skybox light levels and angles based off the current skybox chosen.

defaults to the tf2_sky_04/2fort skybox levels/angles.

**Comment by ghost** [comment]
added skybox solids around perimeter of grid
